[book]
authors = ["Ramses Ladlani"]
multilingual = false
src = "src"
title = "The Rust eBookshelf"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/dieterplex/rust-ebookshelf"

[output.html.search]
enable = false
