name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SHELFBIN: "https://github.com/dieterplex/mdbookshelf/releases/download/v0.3.0/mdbookshelf-x86_64-unknown-linux-gnu.tar.gz"

jobs:
  deploy:
    # mdbook-toc installed with binstall using gnu build binary from 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Install mdbookshelf binary
        run: |
          if ! [ -x "$(command -v mdbookshelf)" ]; then
            curl --location --silent --show-error --fail "$SHELFBIN" | tar -zxf - -C ~/.cargo/bin
          fi

      - uses: taiki-e/install-action@mdbook

      - uses: taiki-e/install-action@v2
        with:
          tool: mdbook-nocomment,mdbook-mermaid,mdbook-toc

      - run: cargo install --locked mdbook-svgbob

      - name: Build
        run: mdbookshelf && mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
