name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Install mdbookshelf binary
        run: curl --location --silent --show-error --fail "https://github.com/dieterplex/mdbookshelf/releases/download/v0.1.4/mdbookshelf-x86_64-unknown-linux-gnu.tar.gz" | tar -xzvvf - -C ~/.cargo/bin

      - name: Build
        run: mdbookshelf && mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
