name: github pages

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 12 * * *'
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  SHELFBIN: "https://github.com/dieterplex/mdbookshelf/releases/download/v0.4.0/mdbookshelf-x86_64-unknown-linux-gnu.tar.gz"

jobs:
  deploy:
    # mdbook-toc installed with binstall using gnu build binary from 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Install mdbookshelf binary
        run: |
          if ! [ -x "$(command -v mdbookshelf)" ]; then
            curl --location --silent --show-error --fail "$SHELFBIN" | tar -zxf - -C ~/.cargo/bin
          fi

      - uses: taiki-e/install-action@v2
        with:
          tool: mdbook,mdbook-nocomment,mdbook-mermaid,mdbook-toc,mdbook-svgbob

      - name: Build
        run: mdbookshelf && mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          exclude_assets: '.docs/cache'
          force_orphan: true
